from . import hr_contract
from . import hr_hn_ihss
from . import hr_hn_rap
from . import hr_hn_isr
from . import hr_salary_rule
from . import hr_hn_benefit_deduction
from . import hr_payslip
from . import hr_salary_rule_category
from . import hr_hn_salary_history
from . import hr_hn_ihss_history
from . import hr_hn_rap_history
from . import hr_hn_isr_history
from . import hr_hn_benefit_deduction_history
from . import hr_department
from . import hr_payslip_run